version: '3.8'

services:
  web:
    build: .
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/apelab
      - SECRET_KEY_BASE=your_secret_key_base
      - PHX_HOST=localhost
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./priv:/app/priv
    command: sh -c "mix ecto.migrate && mix phx.server"

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=apelab
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 